services:
  plantismash-web:
    image: plantismash-web:latest

    user: plantismash

    ports:
      - 8950:8950

    volumes:
      - /local/data/plantismash/plantismash-data:/data/plantismash

  plantismash-backend:
    image: plantismash-backend:latest

    user: plantismash

    ports:
      - 8951:8951

    volumes:
      - /local/data/plantismash/plantismash-data:/data/plantismash

    environment:
      - ANTISMASH_EMAIL_FROM=changeme
      - ANTISMASH_EMAIL_ERROR=null@localhost
      - ANTISMASH_BASE_URL=https://plantismash.bioinformatics.nl
      - TELNET_MAIL_SERVER=changeme
      - TELNET_MAIL_DOMAIN=changeme
